/*
 * This file is generated by jOOQ.
 */
package ca.obrassard.jooqentities;


import ca.obrassard.jooqentities.tables.Lostitems;
import ca.obrassard.jooqentities.tables.Notification;
import ca.obrassard.jooqentities.tables.Users;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>inquirio</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index LOSTITEMS_FK_USERS_FINDERID = Indexes0.LOSTITEMS_FK_USERS_FINDERID;
    public static final Index LOSTITEMS_FK_USERS_OWNERID = Indexes0.LOSTITEMS_FK_USERS_OWNERID;
    public static final Index LOSTITEMS_PRIMARY = Indexes0.LOSTITEMS_PRIMARY;
    public static final Index NOTIFICATION_FK_USERS_SENDERID = Indexes0.NOTIFICATION_FK_USERS_SENDERID;
    public static final Index NOTIFICATION_PRIMARY = Indexes0.NOTIFICATION_PRIMARY;
    public static final Index USERS_PRIMARY = Indexes0.USERS_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index LOSTITEMS_FK_USERS_FINDERID = Internal.createIndex("FK_Users_FinderID", Lostitems.LOSTITEMS, new OrderField[] { Lostitems.LOSTITEMS.FINDERID }, false);
        public static Index LOSTITEMS_FK_USERS_OWNERID = Internal.createIndex("FK_Users_OwnerID", Lostitems.LOSTITEMS, new OrderField[] { Lostitems.LOSTITEMS.OWNERID }, false);
        public static Index LOSTITEMS_PRIMARY = Internal.createIndex("PRIMARY", Lostitems.LOSTITEMS, new OrderField[] { Lostitems.LOSTITEMS.ID }, true);
        public static Index NOTIFICATION_FK_USERS_SENDERID = Internal.createIndex("FK_Users_SenderID", Notification.NOTIFICATION, new OrderField[] { Notification.NOTIFICATION.ITEMID }, false);
        public static Index NOTIFICATION_PRIMARY = Internal.createIndex("PRIMARY", Notification.NOTIFICATION, new OrderField[] { Notification.NOTIFICATION.ID }, true);
        public static Index USERS_PRIMARY = Internal.createIndex("PRIMARY", Users.USERS, new OrderField[] { Users.USERS.ID }, true);
    }
}
