/*
 * This file is generated by jOOQ.
 */
package ca.obrassard.jooqentities;


import ca.obrassard.jooqentities.routines.Cleardb;
import ca.obrassard.jooqentities.routines.Getnearitems;

import javax.annotation.Generated;

import org.jooq.Configuration;


/**
 * Convenience access to all stored procedures and functions in inquirio
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>inquirio.clearDB</code>
     */
    public static void cleardb(Configuration configuration, Integer sure) {
        Cleardb p = new Cleardb();
        p.setSure(sure);

        p.execute(configuration);
    }

    /**
     * Call <code>inquirio.getNearItems</code>
     */
    public static void getnearitems(Configuration configuration, Double lat, Double lng) {
        Getnearitems p = new Getnearitems();
        p.setLat(lat);
        p.setLng(lng);

        p.execute(configuration);
    }
}
