/*
 * This file is generated by jOOQ.
 */
package ca.obrassard.jooqentities;


import ca.obrassard.jooqentities.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in inquirio
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>inquirio.Users</code>.
     */
    public static final Users USERS = ca.obrassard.jooqentities.tables.Users.USERS;
}
