/*
 * This file is generated by jOOQ.
 */
package ca.obrassard.jooqentities.tables.records;


import ca.obrassard.jooqentities.tables.Lostitems;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LostitemsRecord extends UpdatableRecordImpl<LostitemsRecord> implements Record11<Integer, String, String, Double, Timestamp, Integer, Byte, Double, Double, String, Integer> {

    private static final long serialVersionUID = -559356122;

    /**
     * Setter for <code>inquirio.LostItems.Id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>inquirio.LostItems.Id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>inquirio.LostItems.Title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>inquirio.LostItems.Title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>inquirio.LostItems.Description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>inquirio.LostItems.Description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>inquirio.LostItems.Reward</code>.
     */
    public void setReward(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>inquirio.LostItems.Reward</code>.
     */
    public Double getReward() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>inquirio.LostItems.Date</code>.
     */
    public void setDate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>inquirio.LostItems.Date</code>.
     */
    public Timestamp getDate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>inquirio.LostItems.OwnerId</code>.
     */
    public void setOwnerid(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>inquirio.LostItems.OwnerId</code>.
     */
    public Integer getOwnerid() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>inquirio.LostItems.ItemHasBeenFound</code>.
     */
    public void setItemhasbeenfound(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>inquirio.LostItems.ItemHasBeenFound</code>.
     */
    public Byte getItemhasbeenfound() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>inquirio.LostItems.Lattitude</code>.
     */
    public void setLattitude(Double value) {
        set(7, value);
    }

    /**
     * Getter for <code>inquirio.LostItems.Lattitude</code>.
     */
    public Double getLattitude() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>inquirio.LostItems.Longitude</code>.
     */
    public void setLongitude(Double value) {
        set(8, value);
    }

    /**
     * Getter for <code>inquirio.LostItems.Longitude</code>.
     */
    public Double getLongitude() {
        return (Double) get(8);
    }

    /**
     * Setter for <code>inquirio.LostItems.LocationName</code>.
     */
    public void setLocationname(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>inquirio.LostItems.LocationName</code>.
     */
    public String getLocationname() {
        return (String) get(9);
    }

    /**
     * Setter for <code>inquirio.LostItems.FinderID</code>.
     */
    public void setFinderid(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>inquirio.LostItems.FinderID</code>.
     */
    public Integer getFinderid() {
        return (Integer) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, String, Double, Timestamp, Integer, Byte, Double, Double, String, Integer> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, String, Double, Timestamp, Integer, Byte, Double, Double, String, Integer> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Lostitems.LOSTITEMS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Lostitems.LOSTITEMS.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Lostitems.LOSTITEMS.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return Lostitems.LOSTITEMS.REWARD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Lostitems.LOSTITEMS.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Lostitems.LOSTITEMS.OWNERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field7() {
        return Lostitems.LOSTITEMS.ITEMHASBEENFOUND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field8() {
        return Lostitems.LOSTITEMS.LATTITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field9() {
        return Lostitems.LOSTITEMS.LONGITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Lostitems.LOSTITEMS.LOCATIONNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return Lostitems.LOSTITEMS.FINDERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component4() {
        return getReward();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getOwnerid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component7() {
        return getItemhasbeenfound();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component8() {
        return getLattitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component9() {
        return getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getLocationname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getFinderid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getReward();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getOwnerid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value7() {
        return getItemhasbeenfound();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value8() {
        return getLattitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value9() {
        return getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getLocationname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getFinderid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LostitemsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LostitemsRecord value2(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LostitemsRecord value3(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LostitemsRecord value4(Double value) {
        setReward(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LostitemsRecord value5(Timestamp value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LostitemsRecord value6(Integer value) {
        setOwnerid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LostitemsRecord value7(Byte value) {
        setItemhasbeenfound(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LostitemsRecord value8(Double value) {
        setLattitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LostitemsRecord value9(Double value) {
        setLongitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LostitemsRecord value10(String value) {
        setLocationname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LostitemsRecord value11(Integer value) {
        setFinderid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LostitemsRecord values(Integer value1, String value2, String value3, Double value4, Timestamp value5, Integer value6, Byte value7, Double value8, Double value9, String value10, Integer value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LostitemsRecord
     */
    public LostitemsRecord() {
        super(Lostitems.LOSTITEMS);
    }

    /**
     * Create a detached, initialised LostitemsRecord
     */
    public LostitemsRecord(Integer id, String title, String description, Double reward, Timestamp date, Integer ownerid, Byte itemhasbeenfound, Double lattitude, Double longitude, String locationname, Integer finderid) {
        super(Lostitems.LOSTITEMS);

        set(0, id);
        set(1, title);
        set(2, description);
        set(3, reward);
        set(4, date);
        set(5, ownerid);
        set(6, itemhasbeenfound);
        set(7, lattitude);
        set(8, longitude);
        set(9, locationname);
        set(10, finderid);
    }
}
