/*
 * This file is generated by jOOQ.
 */
package ca.obrassard.jooqentities.tables.records;


import ca.obrassard.jooqentities.tables.Notification;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationRecord extends UpdatableRecordImpl<NotificationRecord> implements Record7<Integer, Integer, Integer, byte[], String, Timestamp, Byte> {

    private static final long serialVersionUID = 1139864578;

    /**
     * Setter for <code>inquirio.notification.Id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>inquirio.notification.Id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>inquirio.notification.SenderId</code>.
     */
    public void setSenderid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>inquirio.notification.SenderId</code>.
     */
    public Integer getSenderid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>inquirio.notification.ItemId</code>.
     */
    public void setItemid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>inquirio.notification.ItemId</code>.
     */
    public Integer getItemid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>inquirio.notification.Photo</code>.
     */
    public void setPhoto(byte... value) {
        set(3, value);
    }

    /**
     * Getter for <code>inquirio.notification.Photo</code>.
     */
    public byte[] getPhoto() {
        return (byte[]) get(3);
    }

    /**
     * Setter for <code>inquirio.notification.Message</code>.
     */
    public void setMessage(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>inquirio.notification.Message</code>.
     */
    public String getMessage() {
        return (String) get(4);
    }

    /**
     * Setter for <code>inquirio.notification.Date</code>.
     */
    public void setDate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>inquirio.notification.Date</code>.
     */
    public Timestamp getDate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>inquirio.notification.Visible</code>.
     */
    public void setVisible(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>inquirio.notification.Visible</code>.
     */
    public Byte getVisible() {
        return (Byte) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, byte[], String, Timestamp, Byte> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, byte[], String, Timestamp, Byte> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Notification.NOTIFICATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Notification.NOTIFICATION.SENDERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Notification.NOTIFICATION.ITEMID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field4() {
        return Notification.NOTIFICATION.PHOTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Notification.NOTIFICATION.MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Notification.NOTIFICATION.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field7() {
        return Notification.NOTIFICATION.VISIBLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getSenderid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getItemid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component4() {
        return getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component7() {
        return getVisible();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getSenderid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getItemid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value4() {
        return getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value7() {
        return getVisible();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificationRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificationRecord value2(Integer value) {
        setSenderid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificationRecord value3(Integer value) {
        setItemid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificationRecord value4(byte... value) {
        setPhoto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificationRecord value5(String value) {
        setMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificationRecord value6(Timestamp value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificationRecord value7(Byte value) {
        setVisible(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NotificationRecord values(Integer value1, Integer value2, Integer value3, byte[] value4, String value5, Timestamp value6, Byte value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NotificationRecord
     */
    public NotificationRecord() {
        super(Notification.NOTIFICATION);
    }

    /**
     * Create a detached, initialised NotificationRecord
     */
    public NotificationRecord(Integer id, Integer senderid, Integer itemid, byte[] photo, String message, Timestamp date, Byte visible) {
        super(Notification.NOTIFICATION);

        set(0, id);
        set(1, senderid);
        set(2, itemid);
        set(3, photo);
        set(4, message);
        set(5, date);
        set(6, visible);
    }
}
