/*
 * This file is generated by jOOQ.
 */
package ca.obrassard.jooqentities.routines;


import ca.obrassard.jooqentities.Inquirio;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cleardb extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -420953884;

    /**
     * The parameter <code>inquirio.clearDB.sure</code>.
     */
    public static final Parameter<Integer> SURE = createParameter("sure", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * Create a new routine call instance
     */
    public Cleardb() {
        super("clearDB", Inquirio.INQUIRIO);

        addInParameter(SURE);
    }

    /**
     * Set the <code>sure</code> parameter IN value to the routine
     */
    public void setSure(Integer value) {
        setValue(SURE, value);
    }
}
