/*
 * This file is generated by jOOQ.
 */
package ca.obrassard.jooqentities.routines;


import ca.obrassard.jooqentities.Inquirio;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Getnearitems extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1091874898;

    /**
     * The parameter <code>inquirio.getNearItems.lat</code>.
     */
    public static final Parameter<Double> LAT = createParameter("lat", org.jooq.impl.SQLDataType.DOUBLE, false, false);

    /**
     * The parameter <code>inquirio.getNearItems.lng</code>.
     */
    public static final Parameter<Double> LNG = createParameter("lng", org.jooq.impl.SQLDataType.DOUBLE, false, false);

    /**
     * Create a new routine call instance
     */
    public Getnearitems() {
        super("getNearItems", Inquirio.INQUIRIO);

        addInParameter(LAT);
        addInParameter(LNG);
    }

    /**
     * Set the <code>lat</code> parameter IN value to the routine
     */
    public void setLat(Double value) {
        setValue(LAT, value);
    }

    /**
     * Set the <code>lng</code> parameter IN value to the routine
     */
    public void setLng(Double value) {
        setValue(LNG, value);
    }
}
