/*
 * This file is generated by jOOQ.
 */
package ca.obrassard.jooqentities.routines;


import ca.obrassard.jooqentities.Inquirio;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Updatefounditemcount extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -626861099;

    /**
     * The parameter <code>inquirio.updateFoundItemCount.userID</code>.
     */
    public static final Parameter<Integer> USERID = createParameter("userID", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * Create a new routine call instance
     */
    public Updatefounditemcount() {
        super("updateFoundItemCount", Inquirio.INQUIRIO);

        addInParameter(USERID);
    }

    /**
     * Set the <code>userID</code> parameter IN value to the routine
     */
    public void setUserid(Integer value) {
        setValue(USERID, value);
    }
}
